---
apiVersion: emrcontainers.services.k8s.aws/v1alpha1
kind: VirtualCluster
metadata:
  name: my-ack-vc
spec:
  name: my-ack-vc
  containerProvider:
    id: emr-eks-ack  # your eks cluster name
    type_: EKS
    info:
      eksInfo:
        namespace: emr-data-team-a
