---
apiVersion: emrcontainers.services.k8s.aws/v1alpha1
kind: JobRun
metadata:
  name: my-ack-jobrun-myp7a5be
spec:
  name: my-ack-jobrun-myp7a5be
  virtualClusterRef:
    from:
      name: my-ack-vc
  executionRoleARN: "{emr_on_eks_role_arn}" # emr_on_eks_role_arn for team a from terraform output
  releaseLabel: "emr-6.7.0-latest"
  jobDriver:
    sparkSubmitJobDriver:
      entryPoint: "local:///usr/lib/spark/examples/src/main/python/pi.py"
      entryPointArguments:
      sparkSubmitParameters: "--conf spark.executor.instances=2 --conf spark.executor.memory=1G --conf spark.executor.cores=1 --conf spark.driver.cores=1"
  configurationOverrides: |
    ApplicationConfiguration: null
    MonitoringConfiguration:
      CloudWatchMonitoringConfiguration:
        LogGroupName: /emr-on-eks-logs/emr-eks-ack
        LogStreamNamePrefix: pi-job
      S3MonitoringConfiguration:
        LogUri: s3://emr-eks-ack-rapthg5f
