apiVersion: v1
kind: Pod
metadata:
  name: ny-taxi-driver
  namespace: emr-data-team-a
spec:
  volumes:
    - name: spark-local-dir-1
      hostPath:
        path: /local1
        type: Directory
    - name: spark-local-dir-2
      hostPath:
        path: /local2
        type: Directory

  nodeSelector:
    "NodeGroupType": "spark"

  containers:
    - name: spark-kubernetes-driver # Don't change this name. EMR on EKS looking for this name
      volumeMounts:
        - name: spark-local-dir-1
          mountPath: /data1
          readOnly: false
        - name: spark-local-dir-2
          mountPath: /data2
          readOnly: false
